[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    '@chainlink/contracts/=lib/contracts/src/v0.8/',
    '@uniswap/v3-core/=lib/v3-core/',
]
[profile.zksync]
rpc_url = "https://sepolia.era.zksync.dev"
chain_id = 300
cli = true
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
